# Generated by Django 6.0.1 on 2026-01-12 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True, verbose_name='ID Camera')),
                ('name', models.CharField(max_length=100, verbose_name='Tên camera')),
                ('location', models.CharField(max_length=200, verbose_name='Vị trí')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('maintenance', 'Bảo trì')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Hoạt động lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Danh sách camera',
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('total_students', models.IntegerField(default=0, verbose_name='Tổng số sinh viên')),
                ('attendance_rate', models.FloatField(default=0.0, verbose_name='Tỷ lệ điểm danh (%)')),
                ('avg_scan_time', models.FloatField(default=0.0, verbose_name='Thời gian scan trung bình (s)')),
                ('total_scans', models.IntegerField(default=0, verbose_name='Tổng số lần scan')),
            ],
            options={
                'verbose_name': 'Thống kê hệ thống',
                'verbose_name_plural': 'Thống kê hệ thống',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Lớp')),
                ('face_encoding', models.BinaryField(blank=True, null=True, verbose_name='Face Encoding Data')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/', verbose_name='Ảnh khuôn mặt')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Đã đăng ký khuôn mặt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Danh sách sinh viên',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('late', 'Đi muộn'), ('absent', 'Vắng mặt')], default='present', max_length=10, verbose_name='Trạng thái')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Độ tin cậy nhận diện (%)')),
                ('camera_id', models.CharField(blank=True, max_length=50, verbose_name='ID Camera')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='portal.student')),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Lịch sử điểm danh',
                'ordering': ['-date', '-time_in'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
