# Generated by Django 6.1 on 2026-08-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_attendancesession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, default='', max_length=30)),
                ('assessment_type', models.CharField(default='TOTAL', max_length=40)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portal.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portal.subject')),
            ],
            options={
                'ordering': ['subject__code', 'assessment_type'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'semester', 'assessment_type'), name='uniq_grade_student_subject_semester_type')],
            },
        ),
    ]
