# Generated by Django 6.1 on 2026-08-26 21:13

import django.db.models.deletion
from django.db import migrations, models


def translate_attendance_labels(apps, schema_editor):
    AttendanceRecord = apps.get_model('portal', 'AttendanceRecord')
    labels = {
        'ON_TIME': 'ON TIME',
        'LATE_LEVEL_1': 'LATE — LEVEL 1',
        'LATE_ONE_PERIOD': 'LATE — 1 PERIOD',
        'ABSENT_TWO_PERIODS': 'ABSENT — 2 PERIODS',
        'ABSENT': 'ABSENT',
    }
    for code, label in labels.items():
        AttendanceRecord.objects.filter(attendance_code=code).update(attendance_label=label)


def translate_demo_academic_data(apps, schema_editor):
    Subject = apps.get_model('portal', 'Subject')
    ClassRoom = apps.get_model('portal', 'ClassRoom')
    subject_names = {
        'CNTT301': 'Artificial Intelligence',
        'CNTT302': 'Machine Learning',
        'CNTT303': 'Computer Vision',
        'CNTT304': 'Python Programming',
        'CN333': 'Basic Informatics',
    }
    class_names = {
        'CN23': 'Computer Science Class 2023',
        'CN22A': 'Mathematics',
    }
    for code, name in subject_names.items():
        Subject.objects.filter(code=code).update(name=name)
    for class_id, name in class_names.items():
        ClassRoom.objects.filter(class_id=class_id).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_grade'),
    ]

    operations = [
        migrations.RunPython(translate_attendance_labels, migrations.RunPython.noop),
        migrations.RunPython(translate_demo_academic_data, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', '-time_in'], 'verbose_name': 'Attendance record', 'verbose_name_plural': 'Attendance records'},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Attendance session', 'verbose_name_plural': 'Attendance sessions'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'start_period'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='systemstats',
            options={'ordering': ['-date'], 'verbose_name': 'System statistics', 'verbose_name_plural': 'System statistics'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Status code'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Attendance ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Status label'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_periods',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Counted periods'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='camera_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Camera ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='Recognition confidence (%)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Late minutes'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(default='FACIAL_RECOGNITION', max_length=40, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled time'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='portal.attendancesession', verbose_name='Attendance session'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-in time'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-out time'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(verbose_name='Class date'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance end time'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='external_session_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='External session ID'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='postponed_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='Postponement reason'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='postponed_to',
            field=models.DateField(blank=True, null=True, verbose_name='Postponed to'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance start time'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Camera ID'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last active'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Camera name'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Class ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Class name'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='portal.student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.classroom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_period',
            field=models.IntegerField(choices=[(1, 'Period 1 (7:00 - 7:50)'), (2, 'Period 2 (7:50 - 8:40)'), (3, 'Period 3 (8:50 - 9:40)'), (4, 'Period 4 (9:40 - 10:30)'), (5, 'Period 5 (10:40 - 11:30)'), (6, 'Period 6 (13:00 - 13:50)'), (7, 'Period 7 (13:50 - 14:40)'), (8, 'Period 8 (14:50 - 15:40)'), (9, 'Period 9 (15:40 - 16:30)'), (10, 'Period 10 (16:40 - 17:30)')], verbose_name='End period'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_period',
            field=models.IntegerField(choices=[(1, 'Period 1 (7:00 - 7:50)'), (2, 'Period 2 (7:50 - 8:40)'), (3, 'Period 3 (8:50 - 9:40)'), (4, 'Period 4 (9:40 - 10:30)'), (5, 'Period 5 (10:40 - 11:30)'), (6, 'Period 6 (13:00 - 13:50)'), (7, 'Period 7 (13:50 - 14:40)'), (8, 'Period 8 (14:50 - 15:40)'), (9, 'Period 9 (15:40 - 16:30)'), (10, 'Period 10 (16:40 - 17:30)')], verbose_name='Start period'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Face encoding data'),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/', verbose_name='Face image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Face registered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Subject code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='attendance_rate',
            field=models.FloatField(default=0.0, verbose_name='Attendance rate (%)'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='avg_scan_time',
            field=models.FloatField(default=0.0, verbose_name='Average scan time (s)'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='total_scans',
            field=models.IntegerField(default=0, verbose_name='Total scans'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='total_students',
            field=models.IntegerField(default=0, verbose_name='Total students'),
        ),
    ]
