# Generated by Django 6.0.2 on 2026-02-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày học')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('active', 'Đang điểm danh'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu điểm danh')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc điểm danh')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buổi điểm danh',
                'verbose_name_plural': 'Các buổi điểm danh',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Giảng viên')),
                ('credits', models.IntegerField(default=3, verbose_name='Số tín chỉ')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Danh sách môn học',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ quét mặt'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='portal.attendancesession', verbose_name='Buổi điểm danh'),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Khoa')),
                ('students', models.ManyToManyField(blank=True, related_name='classrooms', to='portal.student', verbose_name='Danh sách sinh viên')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách lớp học',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Thứ')),
                ('start_period', models.IntegerField(choices=[(1, 'Tiết 1 (7:00 - 7:50)'), (2, 'Tiết 2 (7:50 - 8:40)'), (3, 'Tiết 3 (8:50 - 9:40)'), (4, 'Tiết 4 (9:40 - 10:30)'), (5, 'Tiết 5 (10:40 - 11:30)'), (6, 'Tiết 6 (13:00 - 13:50)'), (7, 'Tiết 7 (13:50 - 14:40)'), (8, 'Tiết 8 (14:50 - 15:40)'), (9, 'Tiết 9 (15:40 - 16:30)'), (10, 'Tiết 10 (16:40 - 17:30)')], verbose_name='Tiết bắt đầu')),
                ('end_period', models.IntegerField(choices=[(1, 'Tiết 1 (7:00 - 7:50)'), (2, 'Tiết 2 (7:50 - 8:40)'), (3, 'Tiết 3 (8:50 - 9:40)'), (4, 'Tiết 4 (9:40 - 10:30)'), (5, 'Tiết 5 (10:40 - 11:30)'), (6, 'Tiết 6 (13:00 - 13:50)'), (7, 'Tiết 7 (13:50 - 14:40)'), (8, 'Tiết 8 (14:50 - 15:40)'), (9, 'Tiết 9 (15:40 - 16:30)'), (10, 'Tiết 10 (16:40 - 17:30)')], verbose_name='Tiết kết thúc')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng học')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.classroom', verbose_name='Lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Thời khóa biểu',
                'verbose_name_plural': 'Thời khóa biểu',
                'ordering': ['day_of_week', 'start_period'],
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.schedule', verbose_name='Thời khóa biểu'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('schedule', 'date')},
        ),
    ]
